log_file: "./logs/clf/gird_search/training_results.log"
roc_curves_plots_file: "./plots/clf/grid_search/roc_curves/"
confusion_matrix_plots_file: "./plots/clf/grid_search/confusion_matrix/"



# https://www.kaggle.com/code/prashant111/a-guide-on-xgboost-hyperparameters-tuning
  xgboost_grid_search_params:
    n_estimators: [50, 100]
    max_depth: [3, 5]
    learning_rate: [0.05, 0.1]
    subsample: [0.8]
    colsample_bytree: [0.8]
    gamma: [0, 0.1]
    min_child_weight: [1]
    reg_alpha: [0]
    reg_lambda: [1]
    scale_pos_weight: [1]
    use_gpu: false #Change that to false if your device is not supporting CUDA
    objective: ["binary:logistic"]
    eval_metric: ["logloss"]