log_file: "./logs/outlier_detection/outlier_detection.log"
isolation_forest_folder: "./plots/outlier_detection/isolation_forest"
elliptic_envelope_folder: "./plots/outlier_detection/elliptic_envelope"

isolation_forest_params:
  n_estimators: 1000


elliptic_envelope_params:
  contamination: 0.1